# https://docs.travis-ci.com/user/languages/javascript-with-nodejs
language: node_js
node_js: lts/*
os: linux
dist: xenial

# https://docs.travis-ci.com/user/caching
cache:
  yarn: true
  directories:
    - node_modules

# https://docs.travis-ci.com/user/for-beginners/#builds-stages-jobs-and-phases
# https://docs.travis-ci.com/user/build-stages/#build-stages-and-deployments
jobs:
  # https://docs.travis-ci.com/user/job-lifecycle/
  # https://config.travis-ci.com/ref/jobs
  include:
    - stage: build
      script: yarn build

    - stage: test
      script: yarn test
    - script:
        - yarn test:nyan
        - yarn cov
      after_success:
        - yarn cov:report

    - stage: release
      # https://semantic-release.gitbook.io/semantic-release/recipes/recipes/travis#node-js-projects-configuration
      script: skip
      deploy:
        # https://docs.travis-ci.com/user/deployment#uploading-files-and-skip_cleanup
        provider: script
        script: yarn semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
